export const config = {
  env: process.env.NODE_ENV || 'development',
  port: Number(process.env.PORT || 4000),
  databaseUrl: process.env.DATABASE_URL || 'file:./mint.sqlite',
  // Same fallback as backend/src/utils/jwt.ts so the two implementations agree.
  jwtSecret: process.env.JWT_SECRET || 'mint-dev-secret-change-in-production',
  disableAuth: process.env.DISABLE_AUTH === 'true',
  // Default 'ollama' for local development; users can override.
  llmProvider: process.env.LLM_PROVIDER || 'ollama',
  openaiApiKey: process.env.OPENAI_API_KEY || '',
  googleAiApiKey: process.env.GOOGLE_AI_API_KEY || '',
  dashscopeApiKey: process.env.DASHSCOPE_API_KEY || '',
  ollamaBaseUrl: process.env.OLLAMA_BASE_URL || 'http://localhost:11434',
  researchProvider: process.env.RESEARCH_PROVIDER || 'brave',
  braveSearchApiKey: process.env.BRAVE_SEARCH_API_KEY || '',
  openaiImageApiKey: process.env.OPENAI_IMAGE_API_KEY || '',
  smtpHost: process.env.SMTP_HOST || '',
  smtpPort: Number(process.env.SMTP_PORT || 587),
  smtpUser: process.env.SMTP_USER || '',
  smtpPass: process.env.SMTP_PASS || '',
  emailFrom: process.env.EMAIL_FROM || 'MINT <noreply@mint.local>',
  redisUrl: process.env.REDIS_URL || 'redis://localhost:6379',
  s3Endpoint: process.env.S3_ENDPOINT || '',
  s3AccessKey: process.env.S3_ACCESS_KEY || '',
  s3SecretKey: process.env.S3_SECRET_KEY || '',
  s3Region: process.env.S3_REGION || 'us-east-1',
};
